# Generated by Django 5.0.6 on 2026-04-29 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('enfant', 'Enfant')], default='parent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('time', 'Horaire fixe'), ('device_on', "Quand un objet s'allume"), ('device_off', "Quand un objet s'éteint"), ('manual', 'Manuel uniquement')], default='manual', max_length=20)),
                ('trigger_time', models.TimeField(blank=True, help_text='Heure de déclenchement (si trigger Horaire)', null=True)),
                ('action_type', models.CharField(choices=[('toggle', "Basculer l'état"), ('turn_on', 'Allumer'), ('turn_off', 'Éteindre'), ('set_value', 'Régler une valeur')], max_length=20)),
                ('action_value', models.FloatField(blank=True, help_text='Valeur pour set_value (ex: 22°C)', null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('action_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api.device')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
                ('trigger_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_scenarios', to='api.device')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
