# Generated by Django 5.0.6 on 2026-04-29 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_allowedmember_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServiceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('turn_on', 'Allumer'), ('turn_off', 'Éteindre'), ('toggle', 'Basculer'), ('set_value', 'Régler une valeur'), ('open', 'Ouvrir (volet)'), ('close', 'Fermer (volet)')], max_length=20)),
                ('action_value', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_actions', to='api.device')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
