# Generated by Django 5.0.6 on 2026-04-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_created_by_serviceaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='related_device',
        ),
        migrations.AddField(
            model_name='service',
            name='related_devices',
            field=models.ManyToManyField(blank=True, related_name='services', to='api.device'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
